version: '3'
services:
  db:
    image: mysql
    container_name: basedb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Ci_Cd_DB   
    ports:
      - 3306:3306
    networks:
     - AppNet
     
  spring-boot:
    image: seifeddinebs/validation
    container_name: app
    ports:
      - 8083:8083
    depends_on:
      - db
    networks:
      - AppNet 
    restart: on-failure
networks:
  AppNet: