version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE:       
    ports:
      - 3306:3306
    networks:
     - projectdevops
     
  spring-boot:
    image: bouhmiid/alpine
    container_name: springcontainer
    ports:
      - 8082:8082
    depends_on:
      - database
    networks:
      - projectdevops 
    restart: on-failure
  sonarqube:
    container_name: sonarqube
    image: "sonarqube:8.9.7-community"
    ports:
      - "9001:9001"
    volumes:
     - 'sonarqube_data:/opt/sonarqube/data'
     - 'sonarqube_extensions:/opt/sonarqube/extensions'
     - 'sonarqube_logs:/opt/sonarqube/logs'
    networks:
     - projectdevops

  nexus:
    container_name: nexuspipeline
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8086:8086"
    networks:
     - projectdevops
  
volumes:
  nexus-data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_data:

networks:
  projectdevops: